// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace YouML
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidYouMLPackageString = "011b691b-5843-4ee4-9237-653d14cc6a3e";
        public static Guid guidYouMLPackage = new Guid(guidYouMLPackageString);

        public const string guidYouMLPackageCmdSetString = "42572517-6e7f-4489-8782-6d29ff9de4e2";
        public static Guid guidYouMLPackageCmdSet = new Guid(guidYouMLPackageCmdSetString);

        public const string guidImagesString = "fa669d7c-d935-4e07-8e77-ada920864f29";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int YouMLToolWindowCommandId = 0x0100;
        public const int mainItemMenuGroup = 0x1020;
        public const int extensionSubMenu = 0x2020;
        public const int extensionSubMenuGroup = 0x1021;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}